name: Close stale issues
on:
  workflow_dispatch:
  schedule:
    # Run every day at 1:00 AM UTC.
    - cron: 0 1 * * *

# yamllint disable rule:empty-lines
env:
  CLOSE_MESSAGE: >
    Closing after no activity on this issue for 12 months. 
  WARN_MESSAGE: >
    There has been no activity on this issue for 11 months.
    The help repository works best when sustained engagement moves conversation forward.
    The issue will be closed in 1 month.
    If you are still experiencing this issue on the latest supported versions of Node.js, please leave a comment.
# yamllint enable

jobs:
  stale:
    if: github.repository == 'nodejs/help'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@a20b814fb01b71def3bd6f56e7494d667ddf28da #4.1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 330 # 11 months
          days-before-close: 30
          stale-issue-label: stale
          close-issue-message: ${{ env.CLOSE_MESSAGE }}
          stale-issue-message: ${{ env.WARN_MESSAGE }}
          # max requests it will send per run to the GitHub API before it deliberately exits to avoid hitting API rate limits
          operations-per-run: 30
          remove-stale-when-updated: true
